const configs = {
  access_token: 'eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIyYjI4NzY3MGYyYmJhYTBmNmI4NzdjODBiNmEyNDYzNiIsInN1YiI6IjVlOTQxZTJkY2NiMTVmMDAxNTcwNmU0NCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.guGKxGchYWLRABZHv_lv6vSKslYsuW73na0Hgo5XDyc'
}

export default configs;